name: Linux Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install binutils-mips-linux-gnu build-essential pkg-config git binutils-mips-linux-gnu python3 zlib1g-dev libaudiofile-dev libcapstone-dev
      - name: create archive
        run: |
          mkdir out
          cp /usr/bin/mips-linux-gnu-* out/
          cp /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/lib*mips* out/
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: out
