name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install deps
        run: |
          msys2 -c 'pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-capstone pkgconf make python3 git --noconfirm'
          msys2 -c 'pacman -S gcc --noconfirm'
          msys2 -c 'wget https://github.com/decompals/ido-static-recomp/releases/download/v1.1/ido-5.3-recomp-windows.tar.gz'
          tar -xvzf ido-5.3-recomp-windows.tar.gz -C ido5.3_recomp
      - name: merge gcc toolchain
        run: |
          msys2 -c 'wget https://github.com/n64-tools/gcc-toolchain-mips64/releases/download/latest/gcc-toolchain-mips64-win64.zip'
          unzip gcc-toolchain-mips64-win64.zip -d C:\msys64\mingw64\
      - name: Compile tools
        run: |
          gcc -I . -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s -DN64GRAPHICS_STANDALONE n64graphics.c utils.c -o n64graphics
          gcc -I . -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s -Wno-unused-result displaylist_packer.c -o displaylist_packer
          gcc -I . -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s -DMIO0_STANDALONE libmio0.c -o mio0
          gcc -I . -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s -DTKMK00_STANDALONE libtkmk00.c utils.c -o tkmk00
          gcc -I . -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s -DN64CKSUM_STANDALONE n64cksum.c utils.c -o n64cksum
          gcc -I . -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s extract_data_for_mio.c -o extract_data_for_mio
      - name: create archive
        run: |
          mkdir out
          mkdir out/mingw64
          cp C:/msys64/mingw64/bin -r out/mingw64
          msys2 -c 'cp C:/msys64/usr/bin -fr out/mingw64'
          msys2 -c 'cp C:/mingw64/bin -fr out/mingw64'
          mkdir out/tools
          cp n64graphics* out/tools
          cp displaylist_packer* out/tools
          cp mio0* out/tools
          cp tkmk00* out/tools
          cp n64cksum* out/tools
          cp extract_data_for_mio* out/tools
          cp ido5.3_recomp -r out/tools
          cp C:/msys64/usr/bin/msys-2.0.dll out/tools/ido5.3_recomp
          msys2 -c 'whereis python3'
          msys2 -c 'whereis gcc'
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mips-tools-chain
          path: out
