name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install deps
        run: |
          pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-capstone pkgconf make python3 git --noconfirm
          pacman -S gcc --noconfirm
      - name: build recomp
        run: |
          g++ recomp.cpp -o recomp -g -lcapstone -Dugen53
      - name: build tools
        run: |
          ./recomp ../ido5.3_compiler/usr/lib/as1 > as1_c.c
          ./recomp ../ido5.3_compiler/usr/lib/cc > cc_c.c
          ./recomp ../ido5.3_compiler/usr/lib/cfe > cfe_c.c
          ./recomp ../ido5.3_compiler/usr/lib/copt > copt_c.c
          ./recomp ../ido5.3_compiler/usr/lib/ugen > ugen_c.c
          ./recomp ../ido5.3_compiler/usr/lib/ujoin > ujoin_c.c
          ./recomp ../ido5.3_compiler/usr/lib/uld > uld_c.c
          ./recomp ../ido5.3_compiler/usr/lib/umerge > umerge_c.c
          ./recomp ../ido5.3_compiler/usr/lib/uopt > uopt_c.c