name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install deps
        run: |
          msys2 -c 'pacman -S mingw-w64-x86_64-gcc pkgconf make gcc --noconfirm'
      - name: locate package
        run: |
          where iconv
      - name: merge gcc toolchain
        run: |
          msys2 -c 'wget https://github.com/n64-tools/gcc-toolchain-mips64/releases/download/latest/gcc-toolchain-mips64-win64.zip'
          unzip gcc-toolchain-mips64-win64.zip -d mips-toolchain
          msys2 -c 'cp mips-toolchain/ -r C:/msys64/mingw64'
      - name: Compile tools
        run: |
          msys2 -c 'make'
      - name: Create archive
        run: |
          mkdir out
          mkdir out/mingw64
          msys2 -c 'wget https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-iconv-1.17-3-any.pkg.tar.zst'
          msys2 -c 'zstd -d mingw-w64-x86_64-iconv-*.tar.zst -o iconv.tar'
          msys2 -c 'tar -xvf iconv.tar -C iconv'
          msys2 -c 'cp iconv/mingw64/bin out/mingw64'
          msys2 -c 'wget https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-libiconv-1.17-3-any.pkg.tar.zst'
          msys2 -c 'zstd -d mingw-w64-x86_64-libiconv-*.tar.zst -o libiconv.tar'
          msys2 -c 'tar -xvf libiconv.tar -C libiconv'
          msys2 -c 'cp libiconv/mingw64/bin out/mingw64'
          msys2 -c 'wget https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst'
          msys2 -c 'zstd -d -xvf mingw-w64-x86_64-gettext-*.tar.zst -o gettext.tar'
          msys2 -c 'tar -xvf gettext.tar -C gettext'
          msys2 -c 'cp gettext/mingw64/bin out/mingw64'
          msys2 -c 'cp C:/msys64/mingw64/bin out/mingw64'
          msys2 -c 'cp C:/mingw64/bin/gcc* out/mingw64/bin'
          msys2 -c 'wget https://www.python.org/ftp/python/3.12.1/python-3.12.1-embed-amd64.zip'
          unzip python-3.12.1-embed-amd64.zip -d out/mingw64/bin
          mkdir out/tools
          cp n64graphics* out/tools
          cp displaylist_packer* out/tools
          cp mio0* out/tools
          cp tkmk00* out/tools
          cp n64cksum* out/tools
          cp extract_data_for_mio* out/tools
          mkdir out/tools/ido5.3_recomp
          msys2 -c 'wget https://github.com/decompals/ido-static-recomp/releases/download/v1.1/ido-5.3-recomp-windows.tar.gz'
          tar -xvzf ido-5.3-recomp-windows.tar.gz -C out/tools/ido5.3_recomp
          cp C:/msys64/usr/bin/msys-2.0.dll out/tools/ido5.3_recomp
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mips-tools-chain-windows
          path: out
