name: Windows Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install deps
        run: |
          msys2 -c 'pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-capstone pkgconf make python3 git --noconfirm'
          msys2 -c 'pacman -S gcc --noconfirm'
      - name: merge gcc toolchain
        run: |
          msys2 -c 'wget https://github.com/n64-tools/gcc-toolchain-mips64/releases/download/latest/gcc-toolchain-mips64-win64.zip'
          unzip gcc-toolchain-mips64-win64.zip -d C:\msys64\mingw64\
      - name: build recomp
        run: |
          cd ido5.3_recomp
          msys2 -c 'g++ recomp.cpp -o recomp -g -lcapstone -Dugen53'
      - name: Generate source file
        run: |
          cd ido5.3_recomp
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/as1 > as1_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/bin/cc > cc_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/cfe > cfe_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/copt > copt_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/ugen > ugen_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/ujoin > ujoin_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/uld > uld_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/umerge > umerge_c.c'
          msys2 -c './recomp ../ido5.3_compiler/usr/lib/uopt > uopt_c.c'
      - name: build ido5.3_compiler
        run: |
          cd ido5.3_compiler
          msys2 -c 'gcc libc_impl.c as1_c.c -o as1 -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c cc_c.c -o cc -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c cfe_c.c -o cfe -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c copt_c.c -o copt -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c ugen_c.c -o ugen -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c ujoin_c.c -o ujoin -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c uld_c.c -o uld -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c umerge_c.c -o umerge -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'
          msys2 -c 'gcc libc_impl.c uopt_c.c -o uopt -g -fno-strict-aliasing -lm -no-pie -DIDO53 -O2'